### ISSUE TITLE
Resizing from browser + Error message

### ISSUE THREAD

**Issue by jns117** [Arthur-Milchior/anki-resize-image#21]
Hi, amazing add-on, really appreciate it.
There are two unrelated problems that I have encountered. 
1)When I am resizing images from the browser from card to card, it ends up making the changes to multiple cards sort of like duplicating the card onto other notes, but only happens to the front of the card.

2) The following message has popped up a few times, but I don't understand what it means.

Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-27 10:59:57

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57141)
Traceback (most recent call last):
File "aqt/mediasrv.py", line 111, in send_head
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Me/Library/Application Support/Anki2/Stuff/collection.media/_addons/1103084694/web/images/ui-icons_222222_256x240.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "socketserver.py", line 650, in process_request_thread
File "socketserver.py", line 360, in finish_request
File "http/server.py", line 646, in __init__
File "socketserver.py", line 720, in __init__
File "http/server.py", line 426, in handle
File "http/server.py", line 414, in handle_one_request
File "aqt/mediasrv.py", line 80, in do_GET
File "aqt/mediasrv.py", line 113, in send_head
File "http/server.py", line 481, in send_error
File "socketserver.py", line 799, in write
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

**Comment by Arthur-Milchior** [comment]
Do you know the difference between "card"s and "note"s ? I belivee that what you're describing in 1 is only the fact that you're editing a note and so you see it makes the change to all cards of the notes.

**Comment by jns117** [comment]
Sorry for misusing "card" and "note". Making edits on cards note was affecting other unrelated notes by scrolling through them in the browser.
Is it possible for me to send a screen recording to show what is happening?

**Comment by Arthur-Milchior** [comment]
Yeah, don't hesitate to send a screen recording. That may help.
Sorry for asking this clarification, but some people don't know the difference and I may have expected this to be the cause of the error

**Comment by Arthur-Milchior** [comment]
I just sent a bug report to anki https://anki.tenderapp.com/discussions/ankidesktop/40973-error-in-media-server 
I am really surprised that you are the first to report this error, because I would have expected it to occur sooner. I believe that this is partly a bug of the add-on and partly a bug in anki.

I just uploaded a new version which should correct bug 2. I can't even image why it was looking for the image http://code.jquery.com/ui/1.12.1/themes/base/images/ui-icons_444444_256x240.png in the first place

**Comment by jns117** [comment]
So what happens is it copies what's in the "extra" section of the note onto the other cards, without changing the "text" field. 
Only the note that begins with Dengue fever in the "text" section has the correct corresponding extra field, that was the original. The other notes for some reason copied that section and erased what was previously there.


<img width="1243" alt="1" src="https://user-images.githubusercontent.com/26586227/80395733-520c7a00-88bc-11ea-8ae5-5448823bc4fb.png">
<img width="1238" alt="2" src="https://user-images.githubusercontent.com/26586227/80395756-5769c480-88bc-11ea-8ff3-cfea19d3e7ea.png">
<img width="1239" alt="3" src="https://user-images.githubusercontent.com/26586227/80395763-5a64b500-88bc-11ea-812b-52efb6f20f88.png">
<img width="1236" alt="4" src="https://user-images.githubusercontent.com/26586227/80395764-5b95e200-88bc-11ea-87f0-22d424efa747.png">

**Comment by Arthur-Milchior** [comment]
Can you please try one thing: deactivate the add-on and check whether the problem occur again ?
I can hardly imagine how this problem could occur in the first place, so I would not be entirely surprised if it was related to another add-on.

**Comment by Arthur-Milchior** [comment]
When this occur, in which field do you have your cursor ?
Can you also send me the add-on configuration ?

**Comment by Arthur-Milchior** [comment]
I can also imagine that there is an interaction with another add-on. I'd like you to disable all other add-ons and keep this one only, then check whether the bug still occurs.

If I am right then I'd be happy to discover which add-on interaction creates the problem

**Comment by jns117** [comment]
These are the addons I use. I'll try get the bug with all of them disabled. It occurs when my cursor is in the extra field. I was going through the different cards changing sizes of various images.

![image](https://user-images.githubusercontent.com/26586227/80414286-79257480-88d9-11ea-81e2-fcbb8f4ebdaa.png)

![image](https://user-images.githubusercontent.com/26586227/80414321-893d5400-88d9-11ea-99a3-4cad18d5c45f.png)

**Comment by Arthur-Milchior** [comment]
Thank you. I'll wait for your feedback related to all tests i asked you. I'm really sorry for all the work you have to do

**Comment by jns117** [comment]
I was able to reproduce the bug with all of the other add-ons disabled.

**Comment by jns117** [comment]
If I remove the add-on should I delete the following from the cards styling section?

 /*Start of style added by resize image add-on. Don't edit directly or the edition will be lost. Edit via the add-on configuration */
.mobile .card img {height:unset  !important; width:unset  !important;}
/*End of style added by resize image add-on*/

**Comment by Arthur-Milchior** [comment]
@jns117 
You don't have to remove the style. It'll remain unused, it won't hurt. It just add useless line in the style.

Can you please copy/paste the configuration. I can't reproduce the bug, but if it's a configuration problem, then I need to copy paste it. I don't want to copy it manually

If it's a problem with mac, I fear I don't know how to test, since I don't have one.

 When did the error message you copied popped ?

**Comment by hchang68** [comment]
Dear Arthur,

This is my first time ever posting on Github for an Anki-related inquiry, and I wouldn't have done it otherwise except to say that your add-on has been so extremely helpful for me that I was really sad to discover that this same problem shared by jns117 was also occurring for me. It was actually happening to me for many months, but I tried to deal with it until it got to the point where too many of my cards were being replaced by other cards that I had to reach out to ask you whether there has been any progress made on resolving this bug. 

Your add-on is one of the most important ones I have but I'm saddened that I will not be able to continue using it if this bug persists as it is causing me to lose too many cards whenever they are being transformed into other cards.

Thank you so much.
