### ISSUE TITLE
image resizer

### ISSUE THREAD

**Issue by deelan77** [Arthur-Milchior/anki-resize-image#36]
please i want to delete mine and i cant 
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-16 16:50:46

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Mardan\AppData\Roaming\Anki2\addons21\1214357311\__init__.py", line 415, in reset
    shutil.rmtree(Setup.irFolder)
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 615, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Mardan\\AppData\\Roaming\\Anki2\\addons21\\1214357311\\user_files\\imageResizer.log'

**Comment by lovac42** [comment]
Hold down shift key, then start Anki. That should allow you to delete this addon, then restart Anki.
